//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WarehouseTableDataListReaderProcessResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WarehouseTableDataListReaderProcessResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleApplication1.WarehouseTableDataListReaderProcessResource", typeof(WarehouseTableDataListReaderProcessResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LstMWHTAB00_01.
        /// </summary>
        internal static string API_Method {
            get {
                return ResourceManager.GetString("API_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDBREADMI.
        /// </summary>
        internal static string API_Name {
            get {
                return ResourceManager.GetString("API_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3ApiUserPassword.
        /// </summary>
        internal static string API_Password {
            get {
                return ResourceManager.GetString("API_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3ApiServerPort.
        /// </summary>
        internal static string API_Port {
            get {
                return ResourceManager.GetString("API_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3ApiServerName.
        /// </summary>
        internal static string API_Server {
            get {
                return ResourceManager.GetString("API_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3ApiUserName.
        /// </summary>
        internal static string API_UserName {
            get {
                return ResourceManager.GetString("API_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OV1I.
        /// </summary>
        internal static string Field_Exclude {
            get {
                return ResourceManager.GetString("Field_Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPV1.
        /// </summary>
        internal static string Field_FilterField {
            get {
                return ResourceManager.GetString("Field_FilterField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OV1F.
        /// </summary>
        internal static string Field_FromWarehouseId {
            get {
                return ResourceManager.GetString("Field_FromWarehouseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OV1T.
        /// </summary>
        internal static string Field_ToWarehouseId {
            get {
                return ResourceManager.GetString("Field_ToWarehouseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHTA.
        /// </summary>
        internal static string Field_WarehouseTableId {
            get {
                return ResourceManager.GetString("Field_WarehouseTableId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MWWHLO.
        /// </summary>
        internal static string Value_FilterField {
            get {
                return ResourceManager.GetString("Value_FilterField", resourceCulture);
            }
        }
    }
}
